# permissions for end users to view kuberhealthyjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: kuberhealthyjob-viewer-role
rules:
- apiGroups:
  - kuberhealthy.github.io.kuberhealthy.github.io
  resources:
  - kuberhealthyjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberhealthy.github.io.kuberhealthy.github.io
  resources:
  - kuberhealthyjobs/status
  verbs:
  - get
