# permissions for end users to view kuberhealthychecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: kuberhealthycheck-viewer-role
rules:
- apiGroups:
  - comcast.github.io.comcast.github.io
  resources:
  - kuberhealthychecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - comcast.github.io.comcast.github.io
  resources:
  - kuberhealthychecks/status
  verbs:
  - get
