# permissions for end users to edit kuberhealthyjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: kuberhealthyjob-editor-role
rules:
- apiGroups:
  - comcast.github.io.comcast.github.io
  resources:
  - kuberhealthyjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - comcast.github.io.comcast.github.io
  resources:
  - kuberhealthyjobs/status
  verbs:
  - get
