# permissions for end users to edit kuberhealthystates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: kuberhealthystate-editor-role
rules:
- apiGroups:
  - comcast.github.io.comcast.github.io
  resources:
  - kuberhealthystates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - comcast.github.io.comcast.github.io
  resources:
  - kuberhealthystates/status
  verbs:
  - get
