---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kuberhealthy.kuberhealthy.github.io
  resources:
  - kuberhealthychecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberhealthy.kuberhealthy.github.io
  resources:
  - kuberhealthychecks/finalizers
  verbs:
  - update
- apiGroups:
  - kuberhealthy.kuberhealthy.github.io
  resources:
  - kuberhealthychecks/status
  verbs:
  - get
  - patch
  - update
