prune: # removes descriptions so that the overall file size is small enough to fit into the CRD specification
	cat kuberhealthy.github.io.kuberhealthy.github.io_kuberhealthychecks.yaml | go run remove-descriptions.go > output.yaml
